name: CI/CD github actions

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
         sudo docker build -t workflow:develop .
        env:
         DOCKER_BUILDKIT: 1

      - name: Push Docker Image 
        run: |
         sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
         sudo docker tag workflow:develop ${{ secrets.DOCKER_USERNAME }}/workflow:develop
         sudo docker push ${{ secrets.DOCKER_USERNAME }}/workflow:develop
        env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }} 
          REMOTE_USER: ${{ secrets.VM_USER }} 
          SOURCE: .
          TARGET: /home/tventura/
          SCRIPT_AFTER: |
            sudo docker pull tariqventura/workflow:develop && sudo docker rm -f develop && sudo docker run -d --name develop -p 80:80 tariqventura/workflow:develop
