name: CI/CD

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image develop
        if: github.ref == 'refs/heads/develop'
        run: |
         sudo docker build -t workflow:develop .
        env:
         DOCKER_BUILDKIT: 1

      - name: Push Docker Image develop
        if: github.ref == 'refs/heads/develop'
        run: |
         sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
         sudo docker tag workflow:develop ${{ secrets.DOCKER_USERNAME }}/workflow:develop
         sudo docker push ${{ secrets.DOCKER_USERNAME }}/workflow:develop
        env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to VM develop
        if: github.ref == 'refs/heads/develop'
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }} 
          REMOTE_USER: ${{ secrets.VM_USER }} 
          SOURCE: .
          TARGET: /home/tventura/
          SCRIPT_AFTER: |
            sudo docker pull tariqventura/workflow:develop && sudo docker rm -f develop &&  sudo docker run --restart unless-stopped -d --name develop -p 8080:80 tariqventura/workflow:develop
      
      - name: Build Docker Image master
        if: github.ref == 'refs/heads/master'
        run: |
         sudo docker build -t workflow:master .
        env:
         DOCKER_BUILDKIT: 1

      - name: Push Docker Image master
        if: github.ref == 'refs/heads/master'
        run: |
         sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
         sudo docker tag workflow:master ${{ secrets.DOCKER_USERNAME }}/workflow:master
         sudo docker push ${{ secrets.DOCKER_USERNAME }}/workflow:master
        env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to VM master
        if: github.ref == 'refs/heads/master'
        uses: easingthemes/ssh-deploy@v4.0.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_MASTER }}
          REMOTE_HOST: ${{ secrets.VM_HOST_MASTER }}
          REMOTE_USER: ${{ secrets.VM_USER }} 
          SOURCE: .
          TARGET: /home/tventura/
          SCRIPT_AFTER: |
            sudo docker pull tariqventura/workflow:master && sudo docker rm -f master && sudo docker run --restart unless-stopped -d --name master -p 8080:80 tariqventura/workflow:master
